---
title: "Brazilian eCommerce"
author: Daniel Rabi, Jaswinder Brar
date: June 10, 2026
format: html
editor: visual
embed-resources: TRUE

echo: FALSE
message: FALSE
warning: FALSE
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(DBI)
library(RSQLite)
```

```{r}
data <- DBI::dbConnect(RSQLite::SQLite(), "olist.sqlite")

customers <- DBI::dbReadTable(data, "customersT")
geo_locations <- DBI::dbReadTable(data, "geolocationsT")
order_items <- DBI::dbReadTable(data, "order_itemsT")
order_payments <- DBI::dbReadTable(data, "order_paymentsT")
order_reviews <- DBI::dbReadTable(data, "order_reviewsT")
orders <- DBI::dbReadTable(data, "ordersT")
product_translations <- DBI::dbReadTable(data, "product_category_name_translationsT")
products <- DBI::dbReadTable(data, "productsT")
sellers <- DBI::dbReadTable(data, "sellersT")

DBI::dbDisconnect(data)
```

```{r}
# Cleaning missing values
clean_missing <- function(data){
  data_clean <-  data %>% 
    dplyr::mutate(dplyr::across(tidyselect::where(is.character), ~ dplyr::na_if(stringr::str_trim(.x), "")))
  
  return(data_clean)
}
```

```{r, warning=FALSE}
# Cleaning the data
customers <- customers %>% 
  dplyr::mutate(
    dplyr::across(3, as.numeric)
  ) %>% 
  clean_missing()

geo_locations <- geo_locations %>% 
  dplyr::mutate(
    dplyr::across(1:3, as.numeric)
  ) %>% 
  clean_missing()

order_items <- order_items %>% 
  dplyr::mutate(
    dplyr::across(c(order_item_id, price, freight_value), as.numeric),
    shipping_limit_date = lubridate::ymd_hms(shipping_limit_date)
  ) %>% 
  clean_missing()

order_payments <- order_payments %>% 
  dplyr::mutate(
    dplyr::across(c(2, 4, 5), as.numeric)
  ) %>% 
  clean_missing()

order_reviews <- order_reviews %>% 
  dplyr::mutate(
    dplyr::across(3, as.numeric),
    review_creation_date = lubridate::ymd_hms(review_creation_date),
    review_answer_timestamp = lubridate::ymd_hms(review_answer_timestamp)
  ) %>% 
  clean_missing()

orders <- orders %>% 
  dplyr::mutate(
    order_purchase_timestamp = lubridate::ymd_hms(order_purchase_timestamp),
    order_approved_at = lubridate::ymd_hms(order_approved_at),
    order_delivered_carrier_date = lubridate::ymd_hms(order_delivered_carrier_date),
    order_delivered_customer_date = lubridate::ymd_hms(order_delivered_customer_date),
    order_estimated_delivery_date = lubridate::ymd_hms(order_estimated_delivery_date),
  )

product_translations <- product_translations %>% clean_missing()

products <- products %>% 
  dplyr::mutate(
    dplyr::across(3:9, as.numeric)
  ) %>% 
  clean_missing()

sellers <- sellers %>% 
  dplyr::mutate(
    dplyr::across(2, as.numeric)
  ) %>% 
  clean_missing()
```

```{r}
customers
geo_locations
order_items
order_payments
order_reviews
orders
product_translations
products
sellers
```
